### PR TITLE
Adding all the .py files and the cameras.csv file in data/

### PR DESCRIPTION
**Pull request by pechouc**
# Aim of the Pull Request 

The goal of this pull request is to share the app architecture built locally so far. I have tried to harmonise and document the code as much as possible but it might still be a bit messy as I have worked on it discontinuously and since some parts are directly drawn from tutorials. Let me know if you have any questions of course! 

# Quick description of the files 

## index.py

This file is the main one and the script to run in order to launch the app locally (run "python index.py" in a Terminal and then open http://127.0.0.1:8050/ in your browser). Based on the url path, it calls functions imported from the other .py files in order to build the appropriate page layout. It also contains the callbacks, ie. what brings interactivity to the web-app. 

## alerts.py and risks.py

These files are dedicated respectively to the "Alertes et Infrastructures" and "Niveaux de Risque" dashboards. The main item is the AlertsApp and RisksApp functions that return the corresponding page layout.

## homepage.py

This file is dedicated to the homepage and its main item is the HomePage function that returns the corresponding page layout. It has not been modified from the original [tutorial](https://towardsdatascience.com/create-a-multipage-dash-application-eceac464de91).

## navbar.py 

This file is dedicated to the navigation bar at the top of the web application. Its main component is the Navbar function that instantiates the navigation bar.

## utils.py

This file gathers a few items (variables, functions...) that are common to both dashboards.

# What the app currently looks like

## Homepage 

Beside the navigation bar, the homepage has not been adapted from the original [tutorial](https://towardsdatascience.com/create-a-multipage-dash-application-eceac464de91) yet. 

Capture d’écran 2020-10-10 à 15 25 14

## "Alertes et Infrastructures" dashboard

Accessible from the dropdown at the far-right of the navigation bar, this dashboard simply presents a geographic breakdown of the French metropolitan territory by departments. Hovering one of the departments with your cursor prints its name on the top-right information box. 

Capture d’écran 2020-10-10 à 15 30 57

You can also switch to satellite view by clicking the button right above the map and then, come back to the symbolic layer with the same action. 

Capture d’écran 2020-10-10 à 15 31 55

Finally, if you click on a department, map is automatically zoomed to its borders and markers appear that display the position of the various cameras on the field. 

Capture d’écran 2020-10-10 à 15 34 36

## "Niveaux de Risque" dashboard

Also accessible from the navigation bar, this dashboard presents the same breakdown by departments but the colour of each area is determined by a fake risk score generated randomly from 0 to 1. A colour scale at the bottom left of the map allows the user to interpret it. 

Capture d’écran 2020-10-10 à 15 37 27
The same hovering and zoom-on-click features are enabled, while the position of cameras is not displayed on this dashboard.

### CODE REVIEW

**Comment by frgfm** [comment]
If I may @pechouc, this might be the best time to setup the CI so that we build a docker with the app running, to make sure each PR actually allows the build, and that you can interact with it :) 
I have no experience in dash, but if you let me know about the project dependencies and how to interact with it, let's say using `requests` (or we can just ping it first), I can help setup the Dockerfile and the CI job!

**Review by Akilditu — CHANGES_REQUESTED** [review]
@pechouc thanks a lot for this PR ! 

This is an awesome first step that will allow everyone to interact with a v1 webapp ! 

Maybe you could just correct some lint and other errors reviewed via codacy [here](https://app.codacy.com/gh/pyronear/pyronear-webapp/pullRequest?prid=6305169) so that the PR passes through check.

**Comment by Akilditu** [comment]
> I have no experience with Dash, but if you let me know about the project dependencies and how to interact with it, let's say using `requests` (or we can just ping it first), I can help setup the Dockerfile and the CI job!
@frgfm an update of `requirements.txt` at root would do the job here ?

**Comment by pechouc** [comment]
> If I may @pechouc, this might be the best time to setup the CI so that we build a docker with the app running, to make sure each PR actually allows the build, and that you can interact with it 👍

Indeed, that would be ideal and I would be glad to learn more about all this!

However, I am not sure to precisely understand what information about Dash and the current state of the app you would need? Happy to discuss it in more details but this is really an unknown territory on my side 😅

> Maybe you could just correct some lint and other errors reviewed via codacy here so that the PR passes through checks.

Sure! I hadn't seen these new tests, it's great!

The only "structural" change I was brought to make is to add the `departments.geojson` file to the `data` folder, instead of opening it via `urllib`. 

I am waiting to check that we now pass the Codacy tests and will make final corrections if not.

**Comment by frgfm** [comment]
Correct @Akilditu, just make sure the requirements are accurate along with their versioning!
Also, this might help if the installation and usage instructions in the readme are complete so that I can try to make it work on my own :ok_hand: 

Regarding setting this up @pechouc , I think it's best if I let you guys handling/merging this PR and I'll open one up afterwards and tag you to discuss how to test this ;)

Last note: I understand the `.csv` file if here so that you have basic data to work this, but I would advise in the next PRs to avoid adding too many "content files" in the repo (release attachments are a good alternative to store content files). But here it's pretty understandably needed for now!

**Comment by VincGargasson** [comment]
@pechouc  This is a very good job.
Like you, I'll be keen to check the next PR of @frgfm about the dockers (new field to me also).
I just see on [codady](https://app.codacy.com/gh/pyronear/pyronear-webapp/pullRequest?prid=6305169) that you didn't pass the test because you didn't use double quotes `"`

**Comment by pechouc** [comment]
> I just see on codady that you didn't pass the test because you didn't use double quotes "

I have tried but it does not seem to change the issues detected 😔

I feel like there is an incompatibility between two rules checked by Codacy on the docstrings at the beginning of each Python file. The current version is breaking rule D213 ("Multi-line docstring summary should start at the second line") and if I change it, it is breaking D212 ("Multi-line docstring summary should start at the first line"). 

Is there any way we can deactivate one of these two checks in Codacy? Or do you see ways to circumvent this?

**Comment by frgfm** [comment]
> > I just see on codady that you didn't pass the test because you didn't use double quotes "
> 
> I have tried but it does not seem to change the issues detected 
> 
> I feel like there is an incompatibility between two rules checked by Codacy on the docstrings at the beginning of each Python file. The current version is breaking rule D213 ("Multi-line docstring summary should start at the second line") and if I change it, it is breaking D212 ("Multi-line docstring summary should start at the first line").
> 
> Is there any way we can deactivate one of these two checks in Codacy? Or do you see ways to circumvent this?

Don't worry about Codacy, if there are suggestions that are actually easy to implement (unused imports, etc.), let's look into it but here it's a lint convention that is not taken into account by flake8. Also, the codacy check is non blocking so you can proceed with the PR ;)

**Comment by pechouc** [comment]
> Don't worry about Codacy, if there are suggestions that are actually easy to implement (unused imports, etc.), let's look into it but here it's a lint convention that is not taken into account by flake8. Also, the codacy check is non blocking so you can proceed with the PR ;) (But you do need an approving review though) 

Very clear, thanks! 

@Akilditu I have just re-requested a review from your side since most issues detected by Codacy are now solved. Otherwise, @VincGargasson, I think you can still approve the pull request 😊

**Review by VincGargasson — APPROVED** [review]
Approved as codacy checks are no longer relevant.
I will improve this script later with one of the choosen features.

**Comment by frgfm** [comment]
@pechouc For the sake of documentation, could you add screenshots of how the app renders in the PR description please? (Just need to drag & drop the images at the end). This can be done after merging though, thanks :pray:

**Comment by pechouc** [comment]
Thanks a lot for your approval @VincGargasson and sure, good idea @frgfm! 

I am thus merging this pull request and closing the branch 🎉

Once you have pulled the new version of the repository locally, you will be able to launch the app by running the `index.py` script from a Terminal and opening http://127.0.0.1:8050/ in your browser.

# What the app currently looks like

## Homepage 

Beside the navigation bar, the homepage has not been adapted from the original [tutorial](https://towardsdatascience.com/create-a-multipage-dash-application-eceac464de91) yet. 

Capture d’écran 2020-10-10 à 15 25 14

## "Alertes et Infrastructures" dashboard

Accessible from the dropdown at the far-right of the navigation bar, this dashboard simply presents a geographic breakdown of the French metropolitan territory by departments. Hovering one of the departments with your cursor prints its name on the top-right information box. 

Capture d’écran 2020-10-10 à 15 30 57

You can also switch to satellite view by clicking the button right above the map and then, come back to the symbolic layer with the same action. 

Capture d’écran 2020-10-10 à 15 31 55

Finally, if you click on a department, map is automatically zoomed to its borders and markers appear that display the position of the various cameras on the field. 

Capture d’écran 2020-10-10 à 15 34 36

## "Niveaux de Risque" dashboard

Also accessible from the navigation bar, this dashboard presents the same breakdown by departments but the colour of each area is determined by a fake risk score generated randomly from 0 to 1. A colour scale at the bottom left of the map allows the user to interpret it. 

Capture d’écran 2020-10-10 à 15 37 27
The same hovering and zoom-on-click features are enabled, while the position of cameras is not displayed on this dashboard.

**Pull request merged**
